apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  annotations:
    serving.knative.dev/creator: system:serviceaccount:kserve:kserve-controller-manager
    serving.knative.dev/lastModifier: system:serviceaccount:kserve:kserve-controller-manager
    serving.knative.dev/routes: ltris-bms-dev-0102-predictor-default
  creationTimestamp: "2023-07-24T19:46:17Z"
  generation: 1
  labels:
    app: bms-discovery
    app.kubernetes.io/managed-by: deployment-manager
    component: predictor
    dna.bloomberg.com/application-name: ltris-performance
    ds.bloomberg.com/dolly: dolly
    prqs.bloomberg.com/prqs-number: "0"
    serving.knative.dev/service: ltris-bms-dev-0102-predictor-default
    serving.knative.dev/serviceUID: 55449250-819b-4977-a517-1acef5169777
    serving.kserve.io/inferenceservice: ltris-bms-dev-0102
  name: ltris-bms-dev-0102-predictor-default
  namespace: s-search
  ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: ltris-bms-dev-0102-predictor-default
      uid: 55449250-819b-4977-a517-1acef5169777
  resourceVersion: "2332431081"
  uid: 3f65e9bf-9b7d-4f6b-8a0b-4cda12e6be4f
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/min-scale: "3"
        autoscaling.knative.dev/target: "5"
        autoscaling.knative.dev/targetBurstCapacity: "0"
        bms-discovery.host: "true"
        bms-discovery.http-check: "true"
        bms-discovery.http-check.endpoint: v1/models/ltris-bms-dev-0102
        bms-discovery.http-check.timeout: "600"
        dna.bloomberg.com/alert: '{"matchReason":"InferenceServiceNotReady","actions":{"drqs":{"drqsType":"BF",
          "drqsGroup": 1437, "pwhoId": 3261188, "remediationPlan": "please check this
          README page https://bbgithub.dev.bloomberg.com/disco/search-ltr/tree/master/inference#faqs
          to find instructions or answers on how to solve the issues." }}}'
        dna.bloomberg.com/application-id: bri:si:compute:managed-compute-application:ltris-performance
        dna.bloomberg.com/federation-strategy: None
        dna.bloomberg.com/platform-id: bri:si:compute:managed-compute-platform:dsp
        dna.bloomberg.com/resource-id: bri:si:dsp:inference-service:dsp-dev:ds-pw-dev04:s-search:ltris-bms-dev-0102
        dna.bloomberg.com/tier: bri:si:dsp:managed-compute-tier:dsp-dev
        ds.bloomberg.com.genericresource/last-applied: |
          {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"bms-discovery.host":"true","bms-discovery.http-check":"true","bms-discovery.http-check.endpoint":"v1/models/ltris-bms-dev-0102","bms-discovery.http-check.timeout":"600","dna.bloomberg.com/alert":"{\"matchReason\":\"InferenceServiceNotReady\",\"actions\":{\"drqs\":{\"drqsType\":\"BF\", \"drqsGroup\": 1437, \"pwhoId\": 3261188, \"remediationPlan\": \"please check this README page https://bbgithub.dev.bloomberg.com/disco/search-ltr/tree/master/inference#faqs to find instructions or answers on how to solve the issues.\" }}}","dna.bloomberg.com/application-id":"bri:si:compute:managed-compute-application:ltris-performance","dna.bloomberg.com/federation-strategy":"None","dna.bloomberg.com/platform-id":"bri:si:compute:managed-compute-platform:dsp","dna.bloomberg.com/resource-id":"bri:si:dsp:inference-service:dsp-dev:ds-pw-dev04:s-search:ltris-bms-dev-0102","dna.bloomberg.com/tier":"bri:si:dsp:managed-compute-tier:dsp-dev","identities.bloomberg.com/https":"bcos-secret-dev","serving.kserve.io/enable-metric-aggregation":"true"},"labels":{"app":"bms-discovery","app.kubernetes.io/managed-by":"deployment-manager","dna.bloomberg.com/application-name":"ltris-performance","ds.bloomberg.com/dolly":"dolly","prqs.bloomberg.com/prqs-number":"0"},"name":"ltris-bms-dev-0102","namespace":"s-search"},"spec":{"predictor":{"maxReplicas":3,"minReplicas":3,"sklearn":{"image":"artifactory.inf.bloomberg.com/ds/ext/registry-1.docker.io/kserve/lgbserver:v0.10.2","name":"kserve-container","protocolVersion":"v1","resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"1","memory":"2Gi"}},"storageUri":"https://bcos.dev.blpprofessional.com:8443/v1/solrgen/search_ltr_models/08_01_till_11_01_ablation_top_trial_3.zip"}}}}
        identities.bloomberg.com/https: bcos-secret-dev
        identities.bloomberg.com/initContainerNames: storage-initializer
        internal.serving.kserve.io/storage-initializer-sourceuri: https://bcos.dev.blpprofessional.com:8443/v1/solrgen/search_ltr_models/08_01_till_11_01_ablation_top_trial_3.zip
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
        prometheus.kserve.io/path: /metrics
        prometheus.kserve.io/port: "8080"
        serving.kserve.io/enable-metric-aggregation: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: bms-discovery
        app.kubernetes.io/managed-by: deployment-manager
        component: predictor
        dna.bloomberg.com/application-name: ltris-performance
        ds.bloomberg.com/dolly: dolly
        prqs.bloomberg.com/prqs-number: "0"
        serving.kserve.io/inferenceservice: ltris-bms-dev-0102
    spec:
      containerConcurrency: 0
      containers:
        - args:
            - --model_name=ltris-bms-dev-0102
            - --model_dir=/mnt/models
            - --http_port=8080
          image: artifactory.inf.bloomberg.com/ds/ext/registry-1.docker.io/kserve/lgbserver:v0.10.2
          name: kserve-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
      enableServiceLinks: false
      timeoutSeconds: 300
status:
  conditions:
    - lastTransitionTime: "2023-07-24T19:46:50Z"
      status: "True"
      type: Ready
  latestCreatedRevisionName: ltris-bms-dev-0102-predictor-default-00001
  latestReadyRevisionName: ltris-bms-dev-0102-predictor-default-00001
  observedGeneration: 1
