apiVersion: apps/v1
kind: Deployment
metadata:
  name: guard-service
  labels:
    app: guard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guard-service
  template:
    metadata:
      labels:
        app: guard-service
    spec:
      serviceAccountName: guard-service-account
      containers:
        - name: guard-service
          image: gcr.io/knative-releases/knative.dev/security-guard/cmd/guard-service@sha256:77a21a85ffbf1ff62087d046c86c45ed0b7910b8494fb79b4d78c39580cb7f30
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: GUARD_SERVICE_LOG_LEVEL
              value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: guard-service
spec:
  selector:
    app: guard-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888

---
